export const CHANGE_LINE = 'CHANGE_LINE';
export const FILTER_ORDER_PROCESS = 'FILTER_ORDER_PROCESS';
export const FILTER_ORDER_TECHNICIAN = 'FILTER_ORDER_TECHNICIAN';
export const MODIFY_ORDER = 'MODIFY_ORDER';

